pipeline {
    agent any

    environment {
        TERRAFORM_WORKSPACE = '/home/monpc/Bureau/Restaurant/restaurant/terraform'
    }

    stages {
        stage('Checkout Terraform Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hatemboudabra/terraform-infra.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir(TERRAFORM_WORKSPACE) { // Assurez-vous que ce chemin est correct
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir(TERRAFORM_WORKSPACE) {
                    // Vérifiez que le fichier `terraform.tfvars` existe et est bien configuré
                    sh 'terraform plan -var-file=terraform.tfvars'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir(TERRAFORM_WORKSPACE) {
                    // Appliquez les changements Terraform
                    sh 'terraform apply -auto-approve -var-file=terraform.tfvars'
                }
            }
        }
    }

    post {
        always {
            echo 'Terraform pipeline completed.'
        }
        success {
            echo 'Terraform changes applied successfully!'
        }
        failure {
            echo 'Terraform pipeline failed. Please check the logs for details.'
        }
    }
}
