apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
